### ISSUE TITLE
Doesn't work in Xcode 8

### ISSUE THREAD

**Issue by stanislaw** [kudinovdenis/Xcode-headers-sorting#1]
Hello.

I have followed the installation instructions, opened Xcode 8, and now I am not seeing: `"Sort Alphabetically"` when I right-click on selected headers. Also `Just ctrl+shift+S` doesn't do anything.

What could go wrong? What is a recommended way to debug this?

Output:

```
$ ./install.sh 

copying Service ...

copying sorting script ...

Adding Sort Alphabetically option to the NSUserKeyEquivalents with shortcut...
XCode need to be restarted after install. Close now? (y)es or (n)o: y
```

Thanks.

**Comment by Mallox51** [comment]
Hi! a known issue is "Shortcut is not active on the first file right after XCode launched" 
did you try opening a second file ?

**Comment by stanislaw** [comment]
Yes, I tried opening multiple files. Any ideas how I could debug this?

**Comment by Mallox51** [comment]
Nope sorry. I was just passing by. I did not install the tool.
I was searching for a tool for removing unnecessary imports automatically in Xcode 8

**Comment by stanislaw** [comment]
@Mallox51 did you look at [fui](https://github.com/dblock/fui) ?

**Comment by Mallox51** [comment]
No i'll take a look. thx

**Comment by kudinovdenis** [comment]
@stanislaw 
In my Xcode 8:
![screen shot 2016-10-03 at 17 42 17](https://cloud.githubusercontent.com/assets/3932753/19041504/04eb9d6a-8991-11e6-8b41-21b259c2ff20.png)
It works for both Xcode 8 and Xcode 7 on both of my Mac's

Can you attach files:
~/Library/Preferences/com.apple.dt.Xcode.plist and files inside of ~/Library/Services/ ?

**Comment by stanislaw** [comment]
Ok, interesting: now I see the "Sort Alphabetically" string. The only explanation I can see here is that recently I did delete and install Xcode 8 from scratch (because of other reasons).

I am closing this one, hopefully I am the only one who encountered this.
